services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    user: "0:0"
    restart: unless-stopped
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml:ro
      - /home/luo/.cloudflared/f8bf52ad-d8d7-4b80-bb7e-972efe259877.json:/etc/cloudflared/credentials.json:ro
    extra_hosts:
      - host.docker.internal:host-gateway
