-- 密钥更新与回收结果记录表
CREATE TABLE key_operation_record (
    record_id       BIGINT(20)   NOT NULL AUTO_INCREMENT COMMENT '记录ID',
    key_id          BIGINT(20)   NOT NULL COMMENT '密钥ID',
    user_id         BIGINT(20)   NOT NULL COMMENT '用户ID',
    user_name       VARCHAR(100) DEFAULT NULL COMMENT '用户名',
    key_name        VARCHAR(100) DEFAULT NULL COMMENT '密钥名称',
    encryt_type     VARCHAR(100) DEFAULT NULL COMMENT '算法类型',
    encryt_name     VARCHAR(100) DEFAULT NULL COMMENT '算法名称',
    key_version     INT          DEFAULT NULL COMMENT '密钥版本',
    action_type     VARCHAR(20)  NOT NULL COMMENT '操作类型 UPDATE/REVOKE',
    action_source   VARCHAR(20)  NOT NULL COMMENT '操作来源 MANUAL/AUTO',
    result_status   CHAR(1)      DEFAULT '0' COMMENT '结果状态 0处理中 1成功 2失败',
    chain_status    CHAR(1)      DEFAULT NULL COMMENT '上链状态 0待上链 1成功 2失败',
    chain_hash      VARCHAR(200) DEFAULT NULL COMMENT '交易哈希',
    block_height    BIGINT(20)   DEFAULT NULL COMMENT '区块高度',
    result_message  VARCHAR(500) DEFAULT NULL COMMENT '结果说明',
    receive_status  CHAR(1)      DEFAULT '0' COMMENT '接收状态 0待接收 1已接收',
    action_time     DATETIME     DEFAULT NULL COMMENT '操作时间',
    receive_time    DATETIME     DEFAULT NULL COMMENT '接收时间',
    create_time     DATETIME     DEFAULT NULL COMMENT '创建时间',
    update_time     DATETIME     DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (record_id),
    KEY idx_key_id (key_id),
    KEY idx_user_id (user_id),
    KEY idx_action_type (action_type),
    KEY idx_receive_status (receive_status),
    KEY idx_action_time (action_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='密钥更新与回收结果记录表';
