# Generated by Django 4.2.30 on 2026-09-22 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pqkds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_node',
            field=models.ForeignKey(help_text='交易发送节点', on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='pqkds.node', verbose_name='发送节点'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_node',
            field=models.ForeignKey(blank=True, help_text='交易接收节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='pqkds.node', verbose_name='接收节点'),
        ),
        migrations.AddField(
            model_name='systemparameters',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='sessionkeyinvalidation',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='sessionkeyinvalidation',
            name='invalidated_node',
            field=models.ForeignKey(help_text='密钥更新导致会话失效的节点', on_delete=django.db.models.deletion.CASCADE, related_name='invalidated_sessions', to='pqkds.node', verbose_name='触发失效的节点'),
        ),
        migrations.AddField(
            model_name='sessionkeyinvalidation',
            name='session',
            field=models.ForeignKey(help_text='被失效的会话', on_delete=django.db.models.deletion.CASCADE, related_name='invalidations', to='pqkds.sessionkey', verbose_name='会话'),
        ),
        migrations.AddField(
            model_name='sessionkey',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='sessionkey',
            name='node1',
            field=models.ForeignKey(help_text='会话发起节点', on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_node1', to='pqkds.node', verbose_name='节点1'),
        ),
        migrations.AddField(
            model_name='sessionkey',
            name='node2',
            field=models.ForeignKey(help_text='会话接收节点', on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_node2', to='pqkds.node', verbose_name='节点2'),
        ),
        migrations.AddField(
            model_name='predistributedkey',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='predistributedkey',
            name='node1',
            field=models.ForeignKey(help_text='密钥对的第一个节点', on_delete=django.db.models.deletion.CASCADE, related_name='predist_keys_as_node1', to='pqkds.node', verbose_name='节点1'),
        ),
        migrations.AddField(
            model_name='predistributedkey',
            name='node2',
            field=models.ForeignKey(help_text='密钥对的第二个节点', on_delete=django.db.models.deletion.CASCADE, related_name='predist_keys_as_node2', to='pqkds.node', verbose_name='节点2'),
        ),
        migrations.AddField(
            model_name='predistributedkey',
            name='used_by_session',
            field=models.ForeignKey(blank=True, help_text='消耗此密钥的会话', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predist_key', to='pqkds.sessionkey', verbose_name='使用该密钥的会话'),
        ),
        migrations.AddField(
            model_name='nodekeyversion',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='nodekeyversion',
            name='node',
            field=models.OneToOneField(help_text='关联的节点', on_delete=django.db.models.deletion.CASCADE, related_name='key_versions', to='pqkds.node', verbose_name='节点'),
        ),
        migrations.AddField(
            model_name='node',
            name='blockchain_config',
            field=models.ForeignKey(blank=True, help_text='节点所属的区块链网络配置', null=True, on_delete=django.db.models.deletion.CASCADE, to='pqkds.blockchainconfig', verbose_name='区块链配置'),
        ),
        migrations.AddField(
            model_name='node',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='message',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(help_text='消息接收节点', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='pqkds.node', verbose_name='接收者'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='消息发送节点', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='pqkds.node', verbose_name='发送者'),
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(help_text='消息所属的会话', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pqkds.sessionkey', verbose_name='所属会话'),
        ),
        migrations.AddField(
            model_name='keydistributionlog',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='keydistributionlog',
            name='falcon_keypair',
            field=models.ForeignKey(blank=True, help_text='关联的Falcon密钥对', null=True, on_delete=django.db.models.deletion.CASCADE, to='pqkds.falconkeypair', verbose_name='Falcon密钥对'),
        ),
        migrations.AddField(
            model_name='keydistributionlog',
            name='node',
            field=models.ForeignKey(help_text='操作相关的节点', on_delete=django.db.models.deletion.CASCADE, to='pqkds.node', verbose_name='相关节点'),
        ),
        migrations.AddField(
            model_name='falconkeypair',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='falconkeypair',
            name='node',
            field=models.OneToOneField(help_text='密钥对关联的节点', on_delete=django.db.models.deletion.CASCADE, to='pqkds.node', verbose_name='关联节点'),
        ),
        migrations.AddField(
            model_name='falconkeypair',
            name='system_params',
            field=models.ForeignKey(help_text='关联的系统参数', on_delete=django.db.models.deletion.CASCADE, to='pqkds.systemparameters', verbose_name='系统参数'),
        ),
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together={('node_id_1', 'node_id_2')},
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqkds.chatmessage'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender_id', 'receiver_id', '-timestamp'], name='chat_messag_sender__64c7cc_idx'),
        ),
        migrations.AddField(
            model_name='blockchainconfig',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='block',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddIndex(
            model_name='sessionkeyinvalidation',
            index=models.Index(fields=['session', '-invalidated_at'], name='dvadmin_pqk_session_f4c3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionkeyinvalidation',
            index=models.Index(fields=['invalidated_node', '-invalidated_at'], name='dvadmin_pqk_invalid_2f01c0_idx'),
        ),
        migrations.AddIndex(
            model_name='predistributedkey',
            index=models.Index(fields=['node1', 'node2', 'status', 'algorithm'], name='dvadmin_pqk_node1_i_e882b4_idx'),
        ),
        migrations.AddIndex(
            model_name='predistributedkey',
            index=models.Index(fields=['pool_id'], name='dvadmin_pqk_pool_id_9315a1_idx'),
        ),
        migrations.AddIndex(
            model_name='predistributedkey',
            index=models.Index(fields=['status', 'expires_at'], name='dvadmin_pqk_status_a6f3c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='predistributedkey',
            unique_together={('pool_id', 'key_index')},
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['receiver_id', '-created_at'], name='chat_notifi_receive_f77a88_idx'),
        ),
    ]
