# Generated by Django 4.2.30 on 2026-09-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqkds', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predistributedkey',
            name='payload_algorithm',
            field=models.CharField(choices=[('sm4', '国密 SM4-GCM'), ('aes_256', 'AES-256-GCM（历史数据）')], default='sm4', help_text='被封装的对称密钥所用算法：sm4（新）/ aes_256（历史数据，由迁移脚本回填）', max_length=20, verbose_name='载荷算法'),
        ),
        migrations.AlterField(
            model_name='predistributedkey',
            name='algorithm',
            field=models.CharField(choices=[('kyber_kem', 'Kyber KEM'), ('falcon_lattice', 'Falcon 格密码')], help_text='预分配使用的格密码算法（封装算法）', max_length=20, verbose_name='加密算法'),
        ),
        migrations.AlterField(
            model_name='predistributedkey',
            name='encrypted_key_data',
            field=models.TextField(help_text='使用格密码封装后的对称会话密钥（JSON）', verbose_name='加密的密钥数据'),
        ),
        migrations.AlterField(
            model_name='predistributedkey',
            name='key_hash',
            field=models.CharField(help_text='对称密钥的SHA256哈希，用于校验', max_length=64, verbose_name='密钥哈希'),
        ),
    ]
