# Generated by Django 4.2.30 on 2026-09-24 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqkds', '0004_backfill_payload_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='predistributedkey',
            name='recipient_type',
            field=models.CharField(default='node', help_text='node=节点间预分配；user=分发给用户本人', max_length=10, verbose_name='收件人类型'),
        ),
        migrations.AddField(
            model_name='predistributedkey',
            name='recipient_user_id',
            field=models.BigIntegerField(blank=True, help_text='recipient_type=user 时的 kms.sys_user.user_id（逻辑引用，不建外键）', null=True, verbose_name='收件用户ID'),
        ),
        migrations.AddField(
            model_name='predistributedkey',
            name='source_key_id',
            field=models.BigIntegerField(blank=True, help_text='用户所选非对称密钥的 kms.keymanage.key_id（逻辑引用，不建跨库外键）', null=True, verbose_name='来源密钥ID'),
        ),
        migrations.AddField(
            model_name='predistributedkey',
            name='wrapping_algorithm',
            field=models.CharField(blank=True, help_text='kyber_kem / falcon_lattice / sm2 / sscl；新逻辑一律读写本字段', max_length=20, null=True, verbose_name='封装算法'),
        ),
        migrations.CreateModel(
            name='UserNodeAuthorization',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('user_id', models.BigIntegerField(help_text='kms.sys_user.user_id（逻辑引用，不建跨库外键）', verbose_name='用户ID')),
                ('status', models.CharField(choices=[('active', '有效'), ('revoked', '已撤销')], default='active', max_length=10, verbose_name='状态')),
                ('granted_by', models.CharField(blank=True, help_text='执行授权的管理员', max_length=64, null=True, verbose_name='授权人')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='授权时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('node', models.ForeignKey(help_text='被授权的节点', on_delete=django.db.models.deletion.CASCADE, related_name='user_authorizations', to='pqkds.node', verbose_name='节点')),
            ],
            options={
                'verbose_name': '用户节点授权',
                'verbose_name_plural': '用户节点授权',
                'db_table': 'dvadmin_pqkds_user_node_authorizations',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='dvadmin_pqk_user_id_84aaff_idx')],
                'unique_together': {('user_id', 'node')},
            },
        ),
        migrations.CreateModel(
            name='UserKeyEnvelope',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('batch_id', models.CharField(help_text='一次分发动作的批次号', max_length=64, verbose_name='批次号')),
                ('user_id', models.BigIntegerField(help_text='kms.sys_user.user_id（逻辑引用）', verbose_name='用户ID')),
                ('key_hash', models.CharField(help_text='SM4 密钥的 SHA256，用于核对，不存明文', max_length=64, verbose_name='密钥哈希')),
                ('encrypted_key_data', models.TextField(help_text='用用户所选非对称密钥加密后的 SM4 密钥（JSON：算法 + 密文 + 目标公钥）', verbose_name='加密的密钥数据')),
                ('wrapping_algorithm', models.CharField(help_text='SM2 / SSCL（D17：用户腿只允许这两种）', max_length=20, verbose_name='封装算法')),
                ('source_key_id', models.BigIntegerField(help_text='用户所选非对称密钥 kms.keymanage.key_id', verbose_name='来源密钥ID')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=20, verbose_name='状态')),
                ('expires_at', models.DateTimeField(help_text='固定 24 小时（D8）', verbose_name='过期时间')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '用户对称密钥信封',
                'verbose_name_plural': '用户对称密钥信封',
                'db_table': 'dvadmin_pqkds_user_key_envelopes',
                'ordering': ['-create_datetime'],
                'indexes': [models.Index(fields=['user_id', 'expires_at'], name='dvadmin_pqk_user_id_075fbc_idx'), models.Index(fields=['batch_id'], name='dvadmin_pqk_batch_i_4d066f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DistributionBatch',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('batch_id', models.CharField(max_length=64, unique=True, verbose_name='批次号')),
                ('user_id', models.BigIntegerField(help_text='kms.sys_user.user_id（逻辑引用）', verbose_name='发起用户ID')),
                ('source_key_id', models.BigIntegerField(help_text='用户所选非对称密钥', verbose_name='来源密钥ID')),
                ('wrapping_algorithm', models.CharField(help_text='SM2 / SSCL', max_length=20, verbose_name='封装算法')),
                ('node_ids', models.TextField(help_text='JSON 数组，形如 [1,2,3]', verbose_name='目标节点')),
                ('node_success_count', models.IntegerField(default=0, verbose_name='节点成功数')),
                ('user_envelope_ok', models.BooleanField(default=False, verbose_name='用户信封是否成功')),
                ('status', models.CharField(choices=[('pending', '进行中'), ('partial', '部分成功'), ('success', '全部成功'), ('failed', '失败')], max_length=20, verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '分发批次',
                'verbose_name_plural': '分发批次',
                'db_table': 'dvadmin_pqkds_distribution_batches',
                'ordering': ['-create_datetime'],
                'indexes': [models.Index(fields=['user_id', '-create_datetime'], name='dvadmin_pqk_user_id_69285c_idx'), models.Index(fields=['status'], name='dvadmin_pqk_status_79f881_idx')],
            },
        ),
    ]
