# Generated by Django 4.2.30 on 2026-09-24 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqkds', '0005_add_user_distribution_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predistributedkey',
            name='node1',
            field=models.ForeignKey(help_text='密钥对的第一个节点；用户发起时为收件节点', on_delete=django.db.models.deletion.CASCADE, related_name='predist_keys_as_node1', to='pqkds.node', verbose_name='节点1'),
        ),
        migrations.AlterField(
            model_name='predistributedkey',
            name='node2',
            field=models.ForeignKey(blank=True, help_text='密钥对的第二个节点；recipient_type=user 时为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predist_keys_as_node2', to='pqkds.node', verbose_name='节点2'),
        ),
    ]
