# Generated by Django 4.2.30 on 2026-09-28 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqkds', '0012_falcon_signing_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionKeyConfirmation',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('proof', models.CharField(max_length=64, verbose_name='持有证明')),
                ('key_recovered', models.BooleanField(default=False, help_text='节点声明它已成功解封出 K。服务端无法独立验证这一条，真正起作用的是 proof 的相互匹配。', verbose_name='是否已恢复会话密钥')),
                ('confirmed_at', models.DateTimeField(verbose_name='确认时间')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_confirmations', to='pqkds.node', verbose_name='提交确认的节点')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='pqkds.sessionkey', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '会话确认',
                'verbose_name_plural': '会话确认',
                'db_table': 'dvadmin_pqkds_session_confirmations',
                'unique_together': {('session', 'node')},
            },
        ),
    ]
