# Generated by Django 4.2.30 on 2026-09-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqkds', '0013_sessionkeyconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='key_device_id',
            field=models.CharField(blank=True, default='', help_text='首次上报公钥的设备标识；与该设备本地密钥库一一对应', max_length=128, verbose_name='密钥绑定设备'),
        ),
    ]
