# -*- coding: utf-8 -*-
"""任务书「节点多级授权」：节点授权申请表（外加两处 choices/help_text 对齐）。

任务书《1-课题2-任务书》把「节点多级授权」列为「密钥动态更新与回收系统」的
4 项功能指标之一（p17/p35，由第三方检测机构测试）。本表是"节点发起申请 →
管理员审批 → 双向放行"这条链路的落点。

⚠️ 本迁移是**纯结构变更**，不写任何数据、**不对历史行回填**：
   存量授权关系（`dvadmin_pqkds_user_node_authorizations`）全是管理员手工授的，
   没有对应申请单。编一条"补签申请"比留空更糟（与 0017/0019/0021 同一条纪律）——
   那会让人以为当时走过审批流程。

⚠️ **本表不构成放行判据**。批准动作真的写 `UserNodeAuthorization`；放行永远只读
   那张表（唯一读点 `distribution_service.authorized_node_ids`）。仓库里有过教训：
   `kms-ops/mysql/init/35_remove_permission_request_menu.sql` 记录的那套权限审批
   之所以被整体下线，就因为它的 `approve()` 刻意不授予任何权限，留着只会形成
   **第二套权限语义**。本表只记录过程。

本次一并带上两个 `AlterField`，都是**历史遗留的漂移，不是本次的功能改动**：
  * `nodelongtermkey.status` —— ACTIVE 的展示文案在 2026-10-04 定为「可用」
    （提交 3353a6cf），那条改动只动了 `api_contract.KEY_STATUS_CHOICES`，
    迁移状态没跟上。**只是 choices 标签**，DDL 无变化。
  * `usernodeauthorization.user_id` / `granted_by` —— 本次为"节点↔节点"用途补的
    help_text（说明节点场景下 `user_id` 就是 `Node.sys_user_id`）。同样只改
    文档性文字，DDL 无变化。
"""

# Generated by Django 4.2.30 on 2026-10-08 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqkds', '0021_session_lifecycle_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodelongtermkey',
            name='status',
            field=models.CharField(choices=[('PENDING', '待启用'), ('ACTIVE', '可用'), ('RETIRED', '已被取代'), ('REVOKED', '已回收'), ('EXPIRED', '已过期'), ('LEGACY', '历史记录（只读）')], db_index=True, default='PENDING', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='usernodeauthorization',
            name='granted_by',
            field=models.CharField(blank=True, help_text='执行授权的管理员；节点审批路径写「审批:管理员名」', max_length=64, null=True, verbose_name='授权人'),
        ),
        migrations.AlterField(
            model_name='usernodeauthorization',
            name='user_id',
            field=models.BigIntegerField(help_text='kms.sys_user.user_id（逻辑引用，不建跨库外键）；节点场景下即 Node.sys_user_id', verbose_name='用户ID'),
        ),
        migrations.CreateModel(
            name='NodeAuthorizationRequest',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('cancelled', '已撤回')], default='pending', max_length=10, verbose_name='状态')),
                ('reason', models.CharField(help_text='节点侧填写的用途，展示给审批人', max_length=200, verbose_name='申请理由')),
                ('decided_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='审批人')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('decision_remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='审批意见')),
                ('chain_tx', models.CharField(blank=True, max_length=128, null=True, verbose_name='链上存证哈希')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('requester', models.ForeignKey(help_text='发起申请的节点', on_delete=django.db.models.deletion.CASCADE, related_name='authorization_requests_out', to='pqkds.node', verbose_name='申请节点')),
                ('target', models.ForeignKey(help_text='希望与之建立会话的节点', on_delete=django.db.models.deletion.CASCADE, related_name='authorization_requests_in', to='pqkds.node', verbose_name='目标节点')),
            ],
            options={
                'verbose_name': '节点授权申请',
                'verbose_name_plural': '节点授权申请',
                'db_table': 'dvadmin_pqkds_node_authorization_requests',
                'ordering': ['-create_datetime'],
                'indexes': [models.Index(fields=['status', 'create_datetime'], name='dvadmin_pqk_status_f2ec63_idx'), models.Index(fields=['requester', 'status'], name='dvadmin_pqk_request_ef8ed0_idx'), models.Index(fields=['target', 'status'], name='dvadmin_pqk_target__65f77e_idx')],
            },
        ),
    ]
