# -*- coding: utf-8 -*-
"""授权申请表的**未决去重键**列（并发下"一对节点只有一条 pending"的落点）。

0022 建表时把唯一性当成了"服务层在事务里查一遍"的问题，实测不够：
`select_for_update` 锁的是**已存在的行**，而同一个节点的两个标签页同时点
「申请」时，两边的行都还不存在 —— 两边都插入成功，"同一对节点只允许一条
pending"被绕过。

`pending_key` 在 `pending` 时是 `{申请人id}-{目标id}`、其余状态置 `NULL`，
列上 `unique=True`。MySQL 的唯一索引允许多个 NULL，所以历史行不受限，
而**同时只有一条 pending** 由数据库保证。

⚠️ 纯结构变更，不回填历史（历史行留 NULL 是对的：它们都已离开 pending）。
⚠️ 这一列**只允许经 `node_authorization_service` 写** —— 见模型 docstring。
"""

# Generated by Django 4.2.30 on 2026-10-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqkds', '0022_node_authorization_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeauthorizationrequest',
            name='pending_key',
            field=models.CharField(blank=True, help_text='pending 时 = {申请人id}-{目标id}，其余状态为 NULL', max_length=64, null=True, unique=True, verbose_name='未决去重键'),
        ),
    ]
