# -*- coding: utf-8 -*-
"""授权申请表的**批量提交组号**两列（任务书「选对应的节点列表提交权限确认请求」）。

节点侧一次勾选多个对端、一次提交时，那几条申请共用一个 `batch_id`
（`authreq-<yyyyMMddHHmmss>-<8hex>`，服务端生成）+ 各自的 `batch_seq`。

⚠️ **组只用于展示与批量勾选，没有任何判据读它。** 每条申请仍是独立一行、
   独立状态，管理员可以只批其中几条（部分批准是真实需求）。一旦引入
   "组已批准"并让它参与放行，就是第二套权限语义 —— 仓库为此整体下线过
   一整套审批（见模型 docstring 与 `35_remove_permission_request_menu.sql`）。

⚠️ 纯结构变更，不回填历史（历史行留 NULL 是对的：它们都是单目标提交，
   本来就不属于任何组）。
"""

# Generated by Django 4.2.30 on 2026-10-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqkds', '0023_node_authorization_request_pending_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeauthorizationrequest',
            name='batch_id',
            field=models.CharField(blank=True, help_text='一次多选提交共用一个组号；单目标申请为 NULL', max_length=64, null=True, verbose_name='批量申请组号'),
        ),
        migrations.AddField(
            model_name='nodeauthorizationrequest',
            name='batch_seq',
            field=models.IntegerField(blank=True, help_text='仅用于按提交顺序展示，不参与任何判据', null=True, verbose_name='组内序号'),
        ),
    ]
