# -*- coding: utf-8 -*-
"""两处**纯元数据**变更（无 DDL、不动数据）：

1. `KeyDistributionLog.ACTION_CHOICES` 补 `pool_consume` / `pool_prealloc`
   —— 预分配支线此前**一条流水都不写**，于是「分发记录」页恒空
   （页面没错，是没人写它）。新流程的两条动作从本次起有痕。
2. `PreDistributedKey.recipient_type` 的 help_text 补 `pool` 语义
   —— 池项（未取用）与已交付的信封（`node`）从此是两种**可区分**的形态，
   未取用的资源不会提前出现在接收方的信封列表里。

⚠️ 两项都不改列定义本身（choices/help_text 只影响 Django 层与文档），
   所以**没有数据迁移**：历史行的 `recipient_type` 保持原值。
"""

# Generated by Django 4.2.30 on 2026-10-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqkds', '0024_node_authorization_request_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydistributionlog',
            name='action',
            field=models.CharField(choices=[('system_setup', '系统初始化'), ('partial_key_gen', '部分密钥生成'), ('user_key_gen', '用户密钥生成'), ('blockchain_store', '区块链存储'), ('key_update', '密钥更新'), ('key_revoke', '密钥撤销'), ('pool_consume', '预分配取用（建立会话）'), ('pool_prealloc', '预分配上传')], help_text='执行的操作类型', max_length=30, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='predistributedkey',
            name='recipient_type',
            field=models.CharField(default='node', help_text='pool=预分配池里的待取用资源；node=已取用/已交付给接收节点的信封；user=分发给用户本人', max_length=10, verbose_name='收件人类型'),
        ),
    ]
