# /opt/nginx-proxy/nginx.conf

user  nginx;
worker_processes  auto;
worker_rlimit_nofile 100000; # 关键优化

events {
    worker_connections  20480;
    use epoll;
    multi_accept on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    
    # 高并发下关闭日志以提升 I/O 性能
    access_log  off; 
    
    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;

    # 定义 Upstream
    upstream ruoyi_backend {
        server java-app:8080; # 指向宿主机 Java
        keepalive 32;
    }

    upstream go_key_service {
        server go-app:8081; # 指向宿主机 Go
        keepalive 1000;
    }

    server {
        listen       80;
        server_name  localhost;

        # ========== 安全响应头配置（防止点击劫持攻击） ==========
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Content-Security-Policy "frame-ancestors 'self'" always;
        # ========================================================

        location / {
            root   /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
            index  index.html index.htm;
        }
        
        # 规则 1: 注册 -> Java
        location /keymanage/request/Register {
            proxy_pass http://ruoyi_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }

        # 规则 2: 密钥生成 -> Go
        location /keymanage/request/ {
            proxy_pass http://go_key_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # 10万 TPS 关键配置
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_connect_timeout 5s;
        }

        location /prod-api/ {
            # 转发给 Java
            proxy_pass http://ruoyi_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}