CREATE TABLE IF NOT EXISTS key_distribute_record (
    record_id         BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '记录ID',
    key_id            BIGINT(20)      DEFAULT NULL COMMENT '密钥ID',
    user_id           BIGINT(20)      DEFAULT NULL COMMENT '用户ID',
    user_name         VARCHAR(100)    DEFAULT NULL COMMENT '用户名',
    key_name          VARCHAR(100)    DEFAULT NULL COMMENT '密钥名称',
    encryt_type       VARCHAR(50)     DEFAULT NULL COMMENT '加密算法类型',
    encryt_name       VARCHAR(100)    DEFAULT NULL COMMENT '加密算法名称',
    distribute_type   CHAR(1)         DEFAULT '1' COMMENT '分发类型 (1=初始分发, 2=更新分发, 3=回收后补发)',
    distribute_status CHAR(1)         DEFAULT '0' COMMENT '分发状态 (0=待分发, 1=分发中, 2=分发成功, 3=分发失败)',
    distribute_time   DATETIME        DEFAULT NULL COMMENT '分发时间',
    chain_hash        VARCHAR(200)    DEFAULT NULL COMMENT '区块链交易Hash',
    block_height      BIGINT(20)      DEFAULT NULL COMMENT '区块高度',
    remark            VARCHAR(500)    DEFAULT NULL COMMENT '备注',
    cre_time          DATETIME        DEFAULT NULL COMMENT '创建时间',
    upd_time          DATETIME        DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (record_id),
    KEY idx_key_id (key_id),
    KEY idx_user_id (user_id),
    KEY idx_distribute_type (distribute_type),
    KEY idx_distribute_status (distribute_status),
    KEY idx_distribute_time (distribute_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='密钥分发记录表';
