SET NAMES utf8mb4;
-- key update and revoke operation record table
CREATE TABLE key_operation_record (
    record_id        BIGINT(20)   NOT NULL AUTO_INCREMENT COMMENT 'record id',
    key_id           BIGINT(20)   NOT NULL COMMENT 'key id',
    user_id          BIGINT(20)   NOT NULL COMMENT 'user id',
    user_name        VARCHAR(100) DEFAULT NULL COMMENT 'user name',
    key_name         VARCHAR(100) DEFAULT NULL COMMENT 'key name',
    encryt_type      VARCHAR(100) DEFAULT NULL COMMENT 'algorithm type',
    encryt_name      VARCHAR(100) DEFAULT NULL COMMENT 'algorithm name',
    key_version      INT          DEFAULT NULL COMMENT 'key version',
    action_type      VARCHAR(20)  NOT NULL COMMENT 'operation type UPDATE/REVOKE',
    action_source    VARCHAR(20)  NOT NULL COMMENT 'operation source MANUAL/AUTO',
    result_status    CHAR(1)      DEFAULT '0' COMMENT 'result status 0 pending 1 success 2 failed',
    chain_status     CHAR(1)      DEFAULT NULL COMMENT 'chain status 0 pending 1 success 2 failed',
    chain_hash       VARCHAR(200) DEFAULT NULL COMMENT 'transaction hash',
    block_height     BIGINT(20)   DEFAULT NULL COMMENT 'block height',
    batch_id         VARCHAR(64)  DEFAULT NULL COMMENT 'tree batch id',
    parent_batch_id  VARCHAR(64)  DEFAULT NULL COMMENT 'parent batch id',
    root_batch_id    VARCHAR(64)  DEFAULT NULL COMMENT 'root batch id',
    tree_path        VARCHAR(500) DEFAULT NULL COMMENT 'tree path',
    tree_level       INT          DEFAULT NULL COMMENT 'tree level',
    node_index       INT          DEFAULT NULL COMMENT 'node index',
    expected_count   INT          DEFAULT NULL COMMENT 'expected leaf count',
    tree_fanout      INT          DEFAULT NULL COMMENT 'tree fanout',
    proof_mode       VARCHAR(32)  DEFAULT NULL COMMENT 'proof mode',
    commitment       VARCHAR(128) DEFAULT NULL COMMENT 'update commitment',
    consistency_hash VARCHAR(128) DEFAULT NULL COMMENT 'consistency hash',
    batch_root       VARCHAR(128) DEFAULT NULL COMMENT 'batch root hash',
    proof_path       VARCHAR(2000) DEFAULT NULL COMMENT 'Merkle proof path: R:<hash>|L:<hash>|ROOT:<hash>',
    verify_status    CHAR(1)      DEFAULT NULL COMMENT 'verify status 0 pending 1 success 2 failed',
    verify_message   VARCHAR(500) DEFAULT NULL COMMENT 'verify message',
    result_message   VARCHAR(500) DEFAULT NULL COMMENT 'result message',
    receive_status   CHAR(1)      DEFAULT '0' COMMENT 'receive status 0 pending 1 received',
    action_time      DATETIME     DEFAULT NULL COMMENT 'operation time',
    receive_time     DATETIME     DEFAULT NULL COMMENT 'receive time',
    create_time      DATETIME     DEFAULT NULL COMMENT 'create time',
    update_time      DATETIME     DEFAULT NULL COMMENT 'update time',
    PRIMARY KEY (record_id),
    KEY idx_key_id (key_id),
    KEY idx_user_id (user_id),
    KEY idx_action_type (action_type),
    KEY idx_batch_id (batch_id),
    KEY idx_verify_status (verify_status),
    KEY idx_receive_status (receive_status),
    KEY idx_action_time (action_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='key update and revoke operation record table';
