[cryptoMaterial]
certPath = "conf"
disableSsl = "false"

[network]
peers=["127.0.0.1:20200"]

[account]
keyStoreDir = "account"
accountFileFormat = "pem"

[threadPool]
channelProcessorThreadSize = "16"
receiptProcessorThreadSize = "16"
maxBlockingQueueSize = "102400"
